# DS4200 Homework 4

Due: Friday Mar 28th @ 11:59 PM EST

### Submission Instructions
Submit this `ipynb` file included with the coding results and and two `png` files from the part 3 to Gradescope (this can also be done via the assignment on Canvas).  To ensure that your submitted files represent your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the files to gradescope.

### Tips for success
- Start early
- Make use of Piazza
- Make use of Office hour
- Remember to use cells and headings to make the notebook easy to read (if a grader cannot find the answer to a problem, you will receive no points for it)
- Under no circumstances may one student view or share their ungraded homework or quiz with another student [(see also)](http://www.northeastern.edu/osccr/academic-integrity), though you are welcome to **talk about** (not show each other) the problems.

## Part 1: Altair interactive plots

Gapminder is a non-profit organization that promotes global sustainable development and seeks to bridge the gap between misconceptions and data-driven understanding. We are going to explore the a small subset of its data with the information of average income, health score and population for each country in the world. The region information is also provided.

In [1]:
import altair as alt
import pandas as pd
import geopandas as gpd

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)


import zipfile

with zipfile.ZipFile("crime.csv.zip") as z:
    # List all files inside the ZIP
    for name in z.namelist():
        print(name)

    # Pick the actual CSV (not the __MACOSX one)
    with z.open("crime - crime.csv.csv") as f:
        df = pd.read_csv(f)

# Now df is your DataFrame
df.head()

crime - crime.csv.csv
__MACOSX/._crime - crime.csv.csv

/var/folders/5q/f4fq7xxn49dfgfd3t9j4pwgr0000gn/T/ipykernel_31732/3316792010.py:18: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location
0,I182080058,2403,Disorderly Conduct,DISTURBING THE PEACE,E18,495.0,NaN,2018-10-03 20:13:00,2018,10,Wednesday,20,Part Two,ARLINGTON ST,42.262608,-71.121186,"(42.26260773, -71.12118637)"
1,I182080053,3201,Property Lost,PROPERTY - LOST,D14,795.0,NaN,2018-08-30 20:00:00,2018,8,Thursday,20,Part Three,ALLSTON ST,42.352111,-71.135311,"(42.35211146, -71.13531147)"
2,I182080052,2647,Other,THREATS TO DO BODILY HARM,B2,329.0,NaN,2018-10-03 19:20:00,2018,10,Wednesday,19,Part Two,DEVON ST,42.308126,-71.076930,"(42.30812619, -71.07692974)"
3,I182080051,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,A1,92.0,NaN,2018-10-03 20:00:00,2018,10,Wednesday,20,Part One,CAMBRIDGE ST,42.359454,-71.059648,"(42.35945371, -71.05964817)"
4,I182080050,3122,Aircraft,AIRCRAFT INCIDENTS,A7,36.0,NaN,2018-10-03 20:49:00,2018,10,Wednesday,20,Part Three,PRESCOTT ST,42.375258,-71.024663,"(42.37525782, -71.02466343)"

In [2]:
from shapely.geometry import Point

#Convert to geodataframe

df = df.dropna(subset=["Lat", "Long"])  # remove rows without coordinates
geometry = [Point(xy) for xy in zip(df["Long"], df["Lat"])]
gdf = gpd.GeoDataFrame(df, geometry=geometry, crs="EPSG:4326")

gdf.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,DAY_OF_WEEK,HOUR,UCR_PART,STREET,Lat,Long,Location,geometry
0,I182080058,2403,Disorderly Conduct,DISTURBING THE PEACE,E18,495.0,NaN,2018-10-03 20:13:00,2018,10,Wednesday,20,Part Two,ARLINGTON ST,42.262608,-71.121186,"(42.26260773, -71.12118637)",POINT (-71.12119 42.26261)
1,I182080053,3201,Property Lost,PROPERTY - LOST,D14,795.0,NaN,2018-08-30 20:00:00,2018,8,Thursday,20,Part Three,ALLSTON ST,42.352111,-71.135311,"(42.35211146, -71.13531147)",POINT (-71.13531 42.35211)
2,I182080052,2647,Other,THREATS TO DO BODILY HARM,B2,329.0,NaN,2018-10-03 19:20:00,2018,10,Wednesday,19,Part Two,DEVON ST,42.308126,-71.076930,"(42.30812619, -71.07692974)",POINT (-71.07693 42.30813)
3,I182080051,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,A1,92.0,NaN,2018-10-03 20:00:00,2018,10,Wednesday,20,Part One,CAMBRIDGE ST,42.359454,-71.059648,"(42.35945371, -71.05964817)",POINT (-71.05965 42.35945)
4,I182080050,3122,Aircraft,AIRCRAFT INCIDENTS,A7,36.0,NaN,2018-10-03 20:49:00,2018,10,Wednesday,20,Part Three,PRESCOTT ST,42.375258,-71.024663,"(42.37525782, -71.02466343)",POINT (-71.02466 42.37526)

In [3]:
districts = gpd.read_file("boston_police_districts.geojson").to_crs(epsg=4326)

# map each district to it's name

district_mapping = {
    'A1': 'Charlestown',
    'A15': 'Downtown',
    'A7': 'East Boston',
    'B2': 'Roxbury',
    'B3': 'Mattapan',
    'C11': 'Dorchester',
    'C6': 'South Boston',
    'D14': 'Brighton',
    'D4': 'South End',
    'E13': 'Jamaica Plain',
    'E18': 'Hyde Park',
    'E5': 'West Roxbury'
}


districts['DISTRICT_NAME'] = districts['DISTRICT'].map(district_mapping)
districts.head()

,OBJECTID,DISTRICT,ID,BPDGIS_GIS,DISTRICT_,DISTRICT__,Shape_Length,Shape_Area,shape_wkt,geometry,DISTRICT_NAME
0,1,A15,A15,A,15,15,0.186690,0.000386,None,"MULTIPOLYGON (((-71.07416 42.3905, -71.07416 4...",Downtown
1,2,A7,A7,A,7,07,0.450441,0.001423,None,"MULTIPOLYGON (((-70.99644 42.39556, -70.99644 ...",East Boston
2,3,A1,A1,A,1,01,0.158881,0.000452,None,"POLYGON ((-71.05199 42.36883, -71.05219 42.368...",Charlestown
3,4,C6,C6,C,6,06,0.306182,0.001255,None,"POLYGON ((-71.04406 42.35402, -71.044 42.35413...",South Boston
4,5,D4,D4,D,4,04,0.136961,0.000710,None,"POLYGON ((-71.07416 42.35723, -71.07436 42.357...",South End

In [4]:
joined = gpd.sjoin(gdf, districts, how="left", predicate="within")

joined.head()

,INCIDENT_NUMBER,OFFENSE_CODE,OFFENSE_CODE_GROUP,OFFENSE_DESCRIPTION,DISTRICT_left,REPORTING_AREA,SHOOTING,OCCURRED_ON_DATE,YEAR,MONTH,...,OBJECTID,DISTRICT_right,ID,BPDGIS_GIS,DISTRICT_,DISTRICT__,Shape_Length,Shape_Area,shape_wkt,DISTRICT_NAME
0,I182080058,2403,Disorderly Conduct,DISTURBING THE PEACE,E18,495.0,NaN,2018-10-03 20:13:00,2018,10,...,11.0,E18,E18,E,18.0,18,0.252091,0.001650,None,Hyde Park
1,I182080053,3201,Property Lost,PROPERTY - LOST,D14,795.0,NaN,2018-08-30 20:00:00,2018,8,...,6.0,D14,D14,D,14.0,14,0.189763,0.001255,None,Brighton
2,I182080052,2647,Other,THREATS TO DO BODILY HARM,B2,329.0,NaN,2018-10-03 19:20:00,2018,10,...,12.0,B2,B2,B,2.0,02,0.226925,0.001215,None,Roxbury
3,I182080051,413,Aggravated Assault,ASSAULT - AGGRAVATED - BATTERY,A1,92.0,NaN,2018-10-03 20:00:00,2018,10,...,3.0,A1,A1,A,1.0,01,0.158881,0.000452,None,Charlestown
4,I182080050,3122,Aircraft,AIRCRAFT INCIDENTS,A7,36.0,NaN,2018-10-03 20:49:00,2018,10,...,2.0,A7,A7,A,7.0,07,0.450441,0.001423,None,East Boston

In [7]:
# AGGREGATE

counts = joined.groupby("DISTRICT_").size().reset_index(name="crime_count")

counts.head()

   DISTRICT_  crime_count
0        1.0        33876
1        2.0        48370
2        3.0        34207
3        4.0        40064
4        5.0        12811

In [8]:
import folium

# Merge back with the district shapes
districts = districts.merge(counts, on="DISTRICT_", how="left")
districts["crime_count"] = districts["crime_count"].fillna(0)

In [21]:
# Plot choropleth map

districts.rename(columns={
            "DISTRICT_NAME": "District",
            "crime_count": "Crime Count"
        })

m = districts.explore(
    tiles="CartoDB positron",
    column="Crime Count",
    cmap="OrRd",
    legend=True,
    tooltip=["District", "Crime Count"],
    name="Crime Counts",
    height = "800px"
)

folium.LayerControl().add_to(m)
m

KeyError: 'Crime Count'

In [20]:
import ipywidgets as widgets
from IPython.display import display, clear_output
import folium

offense_options = sorted(joined["OFFENSE_CODE_GROUP"].dropna().unique())

offense_dropdown = widgets.Dropdown(
    options=offense_options,
    value=offense_options[0],
    description='Offense:',
    layout=widgets.Layout(width='60%')
)

out = widgets.Output()

def update_map(change):
    with out:
        clear_output(wait=True)
        
        selected_offense = change['new']
        
        # Filter and aggregate
        filtered = joined[joined["OFFENSE_CODE_GROUP"] == selected_offense]
        counts = filtered.groupby("DISTRICT_").size().reset_index(name="crime_count")

        # Clean + merge counts with district polygons
        updated = districts.drop(columns="crime_count", errors="ignore")
        updated = updated.merge(counts, on="DISTRICT_", how="left")
        updated["crime_count"] = updated["crime_count"].fillna(0)
        updated = updated.rename(columns={
            "DISTRICT_NAME": "District",
            "crime_count": "Crime Count"
        })

        # Plot map
        m = updated.explore(
            column="Crime Count",
            cmap="OrRd",
            legend=True,
            tooltip=["District", "Crime Count"],
            name=f"{selected_offense} Crimes",
            tiles="CartoDB positron",
            height="700px"
        )
        folium.LayerControl().add_to(m)
        display(m)

offense_dropdown.observe(update_map, names='value')

display(offense_dropdown, out)
update_map({'new': offense_dropdown.value})  # show initial map

Dropdown(description='Offense:', layout=Layout(width='60%'), options=('Aggravated Assault', 'Aircraft', 'Arson…

Output()